### ISSUE TITLE
Add StructuredInformation to Transaccion class

### ISSUE THREAD

**Issue by dsande** [VMelnalksnis/NordigenDotNet#101]
**Describe the bug**
Transacciont record does not contains a property to save "remittanceInformationStructured"

**To Reproduce**
Transacctions retrieved from this intitution_id => ABANCA_CAGLESMM needs to get "remittanceInformationStructured" whit the transacction description.

**Expected behavior**
Get the "remittanceInformationStructured" from Nordigen API

	/// <summary>Gets or sets structured information about the transaction, usually added by the debtor.</summary>
	[JsonPropertyName("remittanceInformationStructured")]
	public string StructuredInformation { get; set; } = null!;

**Comment by VMelnalksnis** [comment]
Has been added in [v1.1.1](https://www.nuget.org/packages/VMelnalksnis.NordigenDotNet/1.1.1)

**Comment by dsande** [comment]
Thanks!
