### ISSUE TITLE
Adding support for maskedPan and Details fields 

### ISSUE THREAD

**Issue by itisNathaniel** [VMelnalksnis/NordigenDotNet#164]
**Is your feature request related to a problem? Please describe.**

When looking at some account types, I noticed that the account fields `maskedPan` and `details` are not passed through the library, this PR adds support for these types.

A sample sanitised API response from the `/api/v2/accounts/:id/details/` endpoint:

```
{
    "account": {
        "resourceId": "resource_id",
        "currency": "GBP",
        "ownerName": "Account User",
        "cashAccountType": "CARD",
        "status": "enabled",
        "maskedPan": "XXXX-XXXXXX-12345",
        "details": "A Sample Card"
    }
}
```
**Describe the solution you'd like**
Adding support for the `maskedPan` and `details` items in the API

**Describe alternatives you've considered**

**Additional context**
- Noticed that this field is present and populated in AMEX data feeds

**Comment by VMelnalksnis** [comment]
Was resolved in #174
