### ISSUE TITLE
Bug Missing = after date_from on uri

### ISSUE THREAD

**Issue by uploaded** [VMelnalksnis/NordigenDotNet#31]
Hi,

You missed an "=" in the query after "date_from"

@VMelnalksnis.NordigenDotNet/Accounts/AccountClient.cs		
@public async Task<Transactions> GetTransactions
@line 65
		
uri += $"?date_from{value.Start:yyyy-MM-dd}&date_to={value.End:yyyy-MM-dd}";
        

should be:
uri += $"?date_from={value.Start:yyyy-MM-dd}&date_to={value.End:yyyy-MM-dd}";                      
Thx

**Comment by VMelnalksnis** [comment]
Just published v0.4.4, should be available shortly in nuget.org
